Fix handling of manageCoverage priority
Kitware/CDash pull request #1617
Opened 2023-08-03 19:07 UTC by josephsnyder

As is, the value of the priority in the dropdown in the table was used to set the priority as the very last option, even if the priority was changed using the "Change priority of selected files" capablities.

Change the logic to only use the prioritySelection if it is set and the changePrioritySelected button was not pressed.

Fixes: #1616

2023-08-05 03:35 UTC, williamjallen requested changes

2023-08-05 03:35 UTC, williamjallen commented on app/Http/Controllers/CoverageController.php
> +            $CoverageFile2User->FullPath = htmlspecialchars($_POST['fullpath']);
```suggestion
            $CoverageFile2User->FullPath = htmlspecialchars($_POST['fullpath'] ?? '');
```

2023-08-05 03:35 UTC, williamjallen commented on app/Http/Controllers/CoverageController.php
> +            $CoverageFile2User->SetPriority(intval($_POST['prioritySelection']));
```suggestion
            $CoverageFile2User->SetPriority(intval($_POST['prioritySelection'] ?? -1));
```

2023-08-07 14:06 UTC, josephsnyder commented
Thanks for the suggestions @williamjallen.  Please give it another review when you have the time!

2023-08-07 22:15 UTC, merged